### ISSUE TITLE
explore possible NPM integrations

### ISSUE THREAD

**Issue by lindslewis** [thegabe101/Lindsay-Noah-Gabe-Rojas-Project-2#13]
- [x] by 08/04 before Manatee Tank

**Comment by thegabe101** [comment]
cloudinary looks good for image management

**Comment by lindslewis** [comment]
NPM packages used/selected:

- Chalk (Styling the console for better legibility)
- Cloudinary (Media api  for websites and mobile apps, enables devs to better manage images and videos)
- Mongoose (Connection with Mongo.DB, works directly with schema type files in order to assist in creating models and queries.)
